### ISSUE TITLE
Would you mind providing sample code for running EcoTracker?

### ISSUE THREAD

**Issue by ryanyu512** [hez2010/EcoTracker#5]
as titled. Thanks

**Comment by hez2010** [comment]
I've added a quick start guide, please see README.md.

**Comment by bharathraja** [comment]
adding the include "eco.hpp" after make install in linux, and running the sample code gives this error:


/usr/bin/ld: /tmp/ccHwA3uS.o: in function `eco::ECO::ECO()':
testEcoTracker.cpp:(.text._ZN3eco3ECOC2Ev[_ZN3eco3ECOC5Ev]+0x4c5): undefined reference to `eco::EcoTrain::EcoTrain()'
/usr/bin/ld: /tmp/ccHwA3uS.o: in function `eco::ECO::~ECO()':
testEcoTracker.cpp:(.text._ZN3eco3ECOD2Ev[_ZN3eco3ECOD5Ev]+0xa4): undefined reference to `eco::EcoTrain::~EcoTrain()'
/usr/bin/ld: /tmp/ccHwA3uS.o: in function `eco::ECO::~ECO()':
testEcoTracker.cpp:(.text._ZN3eco3ECOD0Ev[_ZN3eco3ECOD5Ev]+0xad): undefined reference to `eco::EcoTrain::~EcoTrain()'
